steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/steam-378309/steam-v0:$COMMIT_SHA', '.']
- name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/steam-378309/steam-v0:$COMMIT_SHA']
- name: gcr.io/cloud-builders/gcloud
  args: ['run', 'deploy', 'SERVICE_NAME', '--image', 'gcr.io/steam-378309/steam-v0:$COMMIT_SHA', '--platform', 'managed', '--region', 'REGION', '--allow-unauthenticated']
